# -*- coding: utf-8 -*-
"""MiniParcial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PPoqd48bx0BeZbOtSyIuz8hE5yfVX-Ap
"""

class Medico:
    def __init__(self, nombre):
        self.__nombre = nombre

    def get_nombre(self):
        return self.__nombre


class Turno:
    def __init__(self, paciente, medico, fecha):
        self.__paciente = paciente
        self.__medico = medico
        self.__fecha = fecha

    def get_paciente(self):
        return self.__paciente

    def get_medico(self):
        return self.__medico

    def get_fecha(self):
        return self.__fecha


class SistemaTurnos:
    def __init__(self):
        self.__medicos = []
        self.__turnos = []

    def agregar_medico(self, medico):
        self.__medicos.append(medico)

    def buscar_medico(self, nombre):
        for m in self.__medicos:
            if m.get_nombre().lower() == nombre.lower():
                return m
        return None

    def registrar_turno(self, paciente, nombre_medico, fecha):
        medico = self.buscar_medico(nombre_medico)
        if medico is None:
            print("Médico no encontrado.")
            return

        turno = Turno(paciente, medico, fecha)
        self.__turnos.append(turno)
        print("Turno registrado.")

    def mostrar_medicos(self):
        if not self.__medicos:
            print("No hay médicos cargados.")
        for m in self.__medicos:
            print(f"Médico: {m.get_nombre()}")

    def mostrar_turnos(self):
        if not self.__turnos:
            print("No hay turnos registrados.")
        for t in self.__turnos:
            print(f"Paciente: {t.get_paciente()} | Médico: {t.get_medico().get_nombre()} | Fecha: {t.get_fecha()}")


# =======================
#       MENÚ SIMPLE
# =======================

def menu():
    sistema = SistemaTurnos()

    # Médicos precargados
    sistema.agregar_medico(Medico("Dr. Pérez"))
    sistema.agregar_medico(Medico("Dra. Gómez"))

    while True:
        print("\n--- SISTEMA DE TURNOS ---")
        print("1. Listar médicos")
        print("2. Registrar turno")
        print("3. Mostrar turnos")
        print("0. Salir")

        op = input("Opción: ")

        if op == "1":
            sistema.mostrar_medicos()

        elif op == "2":
            paciente = input("Paciente: ")
            nombre_medico = input("Médico: ")
            fecha = input("Fecha (texto): ")
            sistema.registrar_turno(paciente, nombre_medico, fecha)

        elif op == "3":
            sistema.mostrar_turnos()

        elif op == "0":
            print("Fin.")
            break

        else:
            print("Opción inválida.")

menu()